### ISSUE TITLE
Great job !!!

### ISSUE THREAD

**Issue by rajibahmed** [VizuaaLOG/BulmaJS#1]
Nice to see that you are moving forward with the idea .... 
I can add a comment .. not to pollute the global Object space. Rather .. wrap as function and return.
Let the users to decide how they want implement it.

I would say put that into an example or documentation ....   

https://github.com/VizuaaLOG/BulmaJS/blob/6a16f5bf82b58b2171f3d4643c6d040d245f6cbb/src/notification.js#L206

**Comment by VizuaaLOG** [comment]
Are you saying not have a global Bulma object? But rather just have the Notification, Modal etc. functions?

So instead of doing this:
```javascript
new Bulma.Notification(stuff here);
```

users would instead do:
```javascript
new Notification(stuff here);
```

The idea I was going for was to follow in the footsteps of the way jQuery/Bootstrap work whereby you have a single global object that then contains all of the other components. I'm happy for better alternatives though.

**Comment by rajibahmed** [comment]
I am saying you can return an object like this. This plugins can be written in es5
no need to use es6 ...


```javascript
export default (function() {
//Yourcode
return obj
}())
```

Let the user of decided How they want to connect plugins
```javascript
import notifications from 'bulma-notifications';
var Bulma = {};
Bulma['notification']  = notifications
window.Bulma = Bulma || {}
```

Second idea ... write a global plugin ... that creates the global object with connecting smaller simple libs. The other people can just configure the global object as they want. 

Simple dependency injection idea with modularity.

**Comment by VizuaaLOG** [comment]
I think I see what you're saying. We would just be providing the functionality that's required but allow them to choose how they want to implement that into their project. So if they wanted to have the main object of `Foo` they can, and then they can use `new Foo.whatever()`.

**Comment by rajibahmed** [comment]
Yes :)

**Comment by VizuaaLOG** [comment]
I'm researching how other JS implementations for frameworks work and Foundation also follows this, whereby you have a global `Foundation` (Bulma in our case) object which has all of the plugins associated with it.

There is no dependency on any other plugins, if you only want notifications then it can happily work on its own, the only thing it needs is the utils class but this would be part of the processed file anyway.

In my opinion, globals are not a bad thing as long as you use them sparingly. We are only ever going to create a single global `Bulma` and so I don't see an issue with this.

**Edit** I think if someone wanted to not use bulma, then their

**Comment by VizuaaLOG** [comment]
Whoops, thought that was the cancel button ;).

I think the way to go with this, is to have all of the plugins work like you say, whereby we export the plugin, I think I'll keep with ES6 for future proofing, but when we are ready for production all plugins will be transpiled to ES5.

I think we would then have a main `Bulma` file that will have everything in one with the `Bulma` global. Much like how the CSS framework is, whereby the compiled JS file has all plugins via the `Bulma` namespace, and if you would like to customise what you have then you pull in the required src JS files as you need.

**Comment by rajibahmed** [comment]
Yes, try to make sure the Global Bluma plugin is super simple. Then we can use it parts of it ....  not the whole thing. Also creating a global exportable lib gives users to consume on their own namespace. ie.

```
MyCompany = import Bulma stuff ... 
window.MyCompany = MyComapny || {}
```
