### ISSUE TITLE
[Feature request] Panel tabs

### ISSUE THREAD

**Issue by noraj** [VizuaaLOG/BulmaJS#102]
BulmaJS already supports generic [tabs](https://bulma.io/documentation/components/tabs/): https://bulmajs.tomerbe.co.uk/docs/0.10/2-core-components/tabs/

But this won't work and can't be used with `panel-tabs` used in [panel](https://bulma.io/documentation/components/panel/)

**Comment by VizuaaLOG** [comment]
Thank you for this @noraj will look to get something in the 0.12 release.

**Comment by noraj** [comment]
@VizuaaLOG Thanks for your awesome work :tada:

**Comment by VizuaaLOG** [comment]
Hey @noraj,

Do you have an example of the panel tabs being used outside the Bulma docs? The example provided on there are having the tabs act more like filters, this is shown by the fact by default Bulma doesn't include any tab content wrappers for each of the tabs.

Initial thoughts on this make it look like those are more filter buttons, that would not have a generic implementation, rather than being separate tabbed content.

**Comment by noraj** [comment]
I planned to use it on my website, here: https://pwn.by/noraj/publications.html

Instead of creating 2 panels I would have create 1 panel with 2 tabs.

![image](https://user-images.githubusercontent.com/16578570/93272552-064c6580-f7b6-11ea-922f-f53e44032e96.png)

**Comment by VizuaaLOG** [comment]
Hmmm, the content you have there would also follow the filtering style context. For example you would show a list of all of your featured articles with options at the top which via ajax would hide (via a fade out or other means) items that do not match the filter.

Given the example within the documentation theres no way to control the tab content. So to incorporate this it would need custom markup, which I try to avoid as BulmaJS should work out the box with the documentation examples.

I may have a general idea that may help. Basically providing some basic data attributes that can be used go hook up the tabs with the various elements. With some configuration to adjust the initial visibility and then clicking one of the tabs will hide any items that are not inside that filter. That wouldn't require any structural changes to the markup, just some data attributes and I believe is the intended use for the panel.

I may have explained it poorly but I will see if I can get a mockup over the next few days or weeks, might help illustrate what I believe the panel tabs component is intended for. Happy to take alternative views on it though 🙂.

**Comment by noraj** [comment]
> **edit** on second thought after reading the documentation again and looking through github issues, I believe I'm looking to much into it 🙂. It should just behave like tabs, although this will need markup changes like with the main tabs, I do kinda wish Bulma accounted for it as the tab content needs a container that is shown/hidden.

I was going to say it: "Can't it be considered like normal tabs but inside a panel container?".

**Comment by VizuaaLOG** [comment]
0.12.0 has been launched that includes this new plugin 🎉

**Comment by noraj** [comment]
I didn't put a `data-all` attribute and set `is-active` on a `data-target` but by default all panel-block are displayed instead of filtering on the active data-target.

**Comment by VizuaaLOG** [comment]
Hmm thats a good spot, didn't consider con load. Would you mind opening a bug report for this please and ill take a look in the next few days 🙂

**Comment by noraj** [comment]
Here we go: https://github.com/VizuaaLOG/BulmaJS/issues/120
