### ISSUE TITLE
Dropdown menu in navbar

### ISSUE THREAD

**Issue by noraj** [VizuaaLOG/BulmaJS#107]
It seems there is support for standalone **Dropdown** ([Bulma](https://bulma.io/documentation/components/dropdown/), [BulmaJS](https://bulmajs.tomerbe.co.uk/docs/master/2-core-components/dropdown/)) but not **Dropdown menu** ([Bulma](https://bulma.io/documentation/components/navbar/#dropdown-menu)) from the **Navbar** (which is very different).

So would it be possible to support Dropdown menu in navbar?

## Versions

```
bulma 0.9.0
bulmajs 0.11.0
```

**Comment by noraj** [comment]
By the way the native `is-hoverable` class works only with `div` but not with `a` which is also often use on navbars.

**Comment by VizuaaLOG** [comment]
Thank you for the suggestion, this has been implemented and is now in master ready for the 0.12 release. Should you wish to try it out please note master is generally not the most stable, however, documentation can be found within the 'master' section of the documentation.

**Comment by noraj** [comment]
As I'm using the npmjs package, I'll test when it will be release, else I'll to change to much files for just a test. Thank you I'm very eager to test it.

**Comment by noraj** [comment]
Docs: https://bulmajs.tomerbe.co.uk/docs/master/2-core-components/navbar/#dropdown-support

@VizuaaLOG Yeah, it works well, when 0.12 release planned ?

**Comment by VizuaaLOG** [comment]
Hey @noraj,

I've been a bit short on time recently. But planning on getting the panel tabs support in with 0.12 following shortly after. I'm hoping to have it released within a couple weeks or so, unfortunately, it depends on time.

**Comment by noraj** [comment]
I'm using 0.12 now, it rocks. :rocket:
