### ISSUE TITLE
Unable to access the online documentation

### ISSUE THREAD

**Issue by DivadNojnarg** [VizuaaLOG/BulmaJS#111]
**Versions**
BulmaJS: 0.11
Browser: All
Operating system: All

**Describe the bug**
The bulmaJS documentation website is currently unavailable. Tried on multiple platforms (tablet, ...) and different networks.

**To Reproduce**
Go to: https://bulmajs.tomerbe.co.uk/

**Screenshots**
![Screenshot 2020-11-12 at 17 46 51](https://user-images.githubusercontent.com/18291543/98969570-46f30180-250f-11eb-9e19-864ce869345a.png)

**Comment by VizuaaLOG** [comment]
Apologies for this, currently having issues with the server provider again 😡. Am waiting for them to get back to me, but will be moving elsewhere once its back up.

**Comment by VizuaaLOG** [comment]
Just to keep everyone updated on this. I'm currently in the process of moving everything over to a new provider, I'm expecting to have everything sorted by tomorrow. But until then the documentation may be up and down :(.

**Comment by VizuaaLOG** [comment]
Everything should be migrated over now and up and running. Due to the DNS changes over the next few hours it may be hit and miss but should be stable again shortly.

Thanks for reporting!

**Comment by gentilmente** [comment]
@VizuaaLOG hi, is down again

**Comment by VizuaaLOG** [comment]
> @VizuaaLOG hi, is down again

Thanks for letting me know. Should be back up and running.
