### ISSUE TITLE
Support tree table

### ISSUE THREAD

**Issue by quoyi** [VizuaaLOG/BulmaJS#127]
Can you support table tree like this: https://stackoverflow.com/a/59353956/9197815

**Comment by VizuaaLOG** [comment]
Hey @quoyi 

This project aims to be the missing JS package for the Bulma CSS framework. While I'm not ruling out some additional components that tweak existing Bulma features, I believe something like this is outside the scope of this project at the moment, unless Bulma provides the CSS for this (which I don't belive it does, but I I be wrong).

I'm not saying this wouldn't be a useful feature in the future, but I'm afraid it's currently beyond the scope of what BulmaJS is trying to solve.

Thanks for your feature request 😁!

Thanks,
Tom
