### ISSUE TITLE
Window is not defined when using nextjs

### ISSUE THREAD

**Issue by HypeLevels** [VizuaaLOG/BulmaJS#131]
**Versions**
BulmaJS: 0.12.1
Browser: Brave 0.12.1 and Google Chrome 87.0.4280.77 (iOS)
Operating system: Linux, KDE Neon 

**Describe the bug**
When importing BulmaJS in a Next.js application the page doesn't render with the error message written in the title.

**To Reproduce**
1. Add the following import to the top of the component `import Bulma from '@vizuaalog/bulmajs';`
2. Run `yarn dev` or `npm run dev` or `next dev`
3. Load in localhost:3000

**Expected behavior**
I expected BulmaJS to load without any issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/61633775/113675158-f85b2500-96b2-11eb-85d7-bed0ae87de69.png)
![image](https://user-images.githubusercontent.com/61633775/113675212-07da6e00-96b3-11eb-9923-0426beb9dc5f.png)

Not sure if this is something related to Next.js as I haven't tried with another framework or even vanilla html.

**Comment by VizuaaLOG** [comment]
Hey 👋,

This has already been answered a few times, its due to you using a uncompleted version without a build system.

Please see https://github.com/VizuaaLOG/BulmaJS/issues/128

**Comment by HypeLevels** [comment]
Hey! Sorry for bothering, had some time to test now and using the compiled version I get another issue (sadly :( ) since NextJS uses NodeJS to render the app the window object is not defined :(  
![image](https://user-images.githubusercontent.com/61633775/114094894-c0233480-98b4-11eb-997b-207df3e644bc.png)
![image](https://user-images.githubusercontent.com/61633775/114094917-c74a4280-98b4-11eb-8d3b-f446a3be8cb2.png)

**Comment by VizuaaLOG** [comment]
Thanks for checking. Will look get a bug fix out that checks if window is defined before trying to register to it.

A workaround would be use the uncompiled versions and use something like webpack to build them as the individual plugins do not register themselves with window. This is a special case for the compiled versions.

**Comment by HypeLevels** [comment]
Really appreciate the effort!

**Comment by VizuaaLOG** [comment]
Fixed in 0.12.2
