### ISSUE TITLE
Trying to use it in electron, imports problems

### ISSUE THREAD

**Issue by gentilmente** [VizuaaLOG/BulmaJS#137]
**Versions**
BulmaJS: 0.12.1
Electron-forge:  6.0.0
Electron: 16.0.1
Operating system: OS X

**Describe the bug**
*using*
`import Bulma from '@vizuaalog/bulmajs';`

*error*
`Uncaught TypeError: Failed to resolve module specifier "@vizuaalog/bulmajs". Relative references must start with either "/", "./", or "../".`

*using*
`const Bulma = require('@vizuaalog/bulmajs');`

*error*
```Uncaught /Users/gentilmente/Developer/PROYECTOS/BiblioHack/code/bibliohack/node_modules/@vizuaalog/bulmajs/src/bulma.js:3
import Bulma from './core';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)............
```

did `"type": module` in `package.json` nothing changes
did  `import Bulma from '@vizuaalog/bulmajs/dist/bulma.js';`
`Uncaught TypeError: Failed to resolve module specifier "@vizuaalog/bulmajs/dist/bulma.js". Relative references must start with either "/", "./", or "../".`

so I did `import Bulma from '../node_modules/@vizuaalog/bulmajs/dist/bulma.js';`
`Uncaught SyntaxError: The requested module '../node_modules/@vizuaalog/bulmajs/dist/bulma.js' does not provide an export named 'default'`

and `import Bulma from '../node_modules/@vizuaalog/bulmajs';`
`Uncaught TypeError: Failed to resolve module specifier "@vizuaalog/bulmajs/src/`**core**`". Relative references must start with either "/", "./", or "../".`

so thinking in change all imports putting .js in those paths but i guess there must be a better way.

**Comment by VizuaaLOG** [comment]
Do you have other imports in the same project that are working okay?

**Comment by gentilmente** [comment]
Hi, yes. I have another imports.
I notice is something about electron config, not very clear exactly what.
Something with
```
      contextIsolation: false,
      nodeIntegration: true,
```

If I do `const Bulma = require('@vizuaalog/bulmajs');` it works.
When I have a clear understanding, I'll brind some answers
