### ISSUE TITLE
Creating modal: A plugin requires a root and/or a parent.

### ISSUE THREAD

**Issue by pabenito** [VizuaaLOG/BulmaJS#146]
**Versions**
BulmaJS: 0.12.2
Browser: firefox
Operating system: linux

**Describe the bug**
I downloaded the dist file and tried to show a modal with a button, but got the error: `Uncaught Error: A plugin requires a root and/or a parent.`

It's thrown at: `if (l(this, e), t.root = n instanceof a.default ? n._elem : n, this.config = new i.default(o({}, this.constructor.defaultConfig(), t)), !n && !this.config.has("parent")) throw new Error("A plugin requires a root and/or a parent.");` in `modal.js`

**To Reproduce**
1. Create a `modal.html` in root directory with the following code:
```
<!doctype html>
<html lang="es" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>

<body>
    <div id="myModal" class="modal">
        <div class="modal-background"></div>

        <div class="modal-content">
            <div class="box">
                <p>Modal JS example</p>
                <!-- Your content -->
            </div>
        </div>

        <button class="modal-close is-large" aria-label="close"></button>
    </div>
    <script src="./js/bulmajs0.12.2/modal.js"></script>
    <script>
        var modal = Bulma.create('modal', {
            element: document.querySelector('#myModal')
        });

        // You can now call methods on modal
        modal.open();
    </script>
</body>
```
2. Download [release 0.12.2](https://github.com/VizuaaLOG/BulmaJS/releases/tag/0.12.2) in a subdir named `js`
3. Extract file in `js` folder
4. Move `js/BulmaJS-0.12.2/dist` to `js/bulmajs0.12.2` 
5. Open `module.html` in browser.
6. Open js condole.

**Expected behavior**
Is expected to open the modal, but error the is thrown.

**Comment by VizuaaLOG** [comment]
Please see the ES5 section of the install page on the docs. https://bulmajs.tomerbe.co.uk/docs/0.12/1-getting-started/2-installation/

You're trying to use the unbundled version of the modal plugin without a bundler.
