### ISSUE TITLE
Use classes instead of data- attributes

### ISSUE THREAD

**Issue by VizuaaLOG** [VizuaaLOG/BulmaJS#20]
I think that moving forward using the Bulma classes to grab elements is better than using the data-* attributes.

- [x] Accordion
- [x] Calendar
- [x] Dropdown
- [x] File
- [x] Message
- [x] Modal
- [x] Navbar
- [x] Notification
- [x] Tabs
- [x] Update documentation

**Comment by chez14** [comment]
So are you intended to use class based event binding instead of using `data-bulma`?

**Comment by VizuaaLOG** [comment]
This is correct. For example instead of requiring the HTML to be updated with `data-bulma="notification` it will instead bind into how Bulma works using the base classes it has implemented. So the plan is that no HTML changes will be needed to make use of these plugins.
