### ISSUE TITLE
File Upload Path

### ISSUE THREAD

**Issue by Markyb0y** [VizuaaLOG/BulmaJS#23]
I would like to have the option to display the full selected file path or just the filename
maybe a second field so that both could be collected even though only 1 option shown?
consider a form where the file is selected but when a run button is pressed we need to know the full path to import the contents etc, or that some people just prefer to see the full path
thanks

**Comment by Markyb0y** [comment]
so if its not possible to have the path how do I deal with the selected file? I dont mind it only displaying the filename, but once selected I want to be able to read the contents of the file?

**Comment by VizuaaLOG** [comment]
If you're reading it server side, the form's post will contain the file that the server can then process. If you're trying to read it in JS [then this answer may help](https://stackoverflow.com/a/29176118).
