### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by VizuaaLOG** [VizuaaLOG/BulmaJS#26]
While working on the updated docs, I realised there is no Tab plugin. Whoops :(

- [x] Create the plugin logic
- [x] Add the documentation
- [x] Test the functionality
- [x] Push to master

**Comment by diomed** [comment]
yup. is this coming soon? was looking for it.

**Comment by VizuaaLOG** [comment]
I've been crazy busy at work the past few weeks but hope to sit down and work on a few things including tabs soon.

**Comment by VizuaaLOG** [comment]
A basic tabs implementation has been added in 0.4
