### ISSUE TITLE
Can we inject elements params and validate bulma classes?

### ISSUE THREAD

**Issue by rajibahmed** [VizuaaLOG/BulmaJS#3]
If you will create a global Bulma js, that's job will be setting up everything. Shouldn't this should go there, instead hard coding it here ?

https://github.com/VizuaaLOG/BulmaJS/blob/6a16f5bf82b58b2171f3d4643c6d040d245f6cbb/src/notification.js#L178

**Comment by VizuaaLOG** [comment]
Yes, what you are saying is valid. We might as well have the core do the searching and delegate to each plugin to allow it to them setup.

I created a new branch and commit making that change. I don't see a problem with that, but if you do please let me know.

**Comment by rajibahmed** [comment]
I have read through the code base. Seem like a nice implementation :) 👍 
I am confused about the file naming. which file should developer include to get the functionality of notification ?

**Comment by rajibahmed** [comment]
I looked at html docs now @ https://vizuaalog.github.io/BulmaJS/

I would prefer the api to be more simple

``` js
// Import BulmaJS core and plugins
import Bulma from 'path/to/bulmajs/src/core';
import Notification from 'path/to/bulmajs/src/plugins/Notification';

// Register plugins with the core
Bulma.registerPlugin('notification', Notification);

// If you want to use the DOM API, execute the following function
// when the DOM has loaded
Bulma.traverseDOM();

// If you would like global access to Bulma
window.Bulma = Bulma; // This can be anything you wan

```

My preference would be, I am not 100 % sure how to do this.
But calling classes plugin seems limiting to me. Naming something plugins give it a 
bit of limitation IMO. 

```js
// Import BulmaJS core and plugins
import Bulma from 'path/to/bulmajs/src/core';
import Notification from 'path/to/bulmajs/src/plugins/Notification';

let notification_elements = $('.notification') || document.getElementByClassname('.notifications')

Notification.track(notification_elements); // can pass in options 
Dropdown.track(dropdown_elements, options);

Bulma.connect(Notification, Dropdown); //variable args list

// If you would like global access to Bulma
window.Bulma = Bulma; // This can be anything you wan
```

**Comment by VizuaaLOG** [comment]
I don't see a problem at the moment with the current way things work.

I think for simplicity and being able to just 'drop' the JS to quickly prototyping, manually setting up every plugin to look through the HTML is a little bit overkill. I prefer the current way where the `data-` tags are used. If someone doesn't like this method, then they can not use the `data-` API and instead create the instances themselves through the regular JS API.
