### ISSUE TITLE
NPM package is 0.3.1, missing 0.4

### ISSUE THREAD

**Issue by david-nguyen** [VizuaaLOG/BulmaJS#34]
Hello, your NPM package seems to be out of sync and does not contain the 0.4.0 version. Found this out when I tried to include tabs but tabs key could not be found.

https://www.npmjs.com/package/@vizuaalog/bulmajs

**Comment by VizuaaLOG** [comment]
Hey David!

Thank you for reporting that! Looks like I have forgotten to tag a 0.4.0 version. Should be able to tag it in an hour or so.

Glad your using the library. If you have any contributions or feature requests please file an issue :blush:

**Comment by VizuaaLOG** [comment]
A 0.4.0 release has now been tagged. May take a few minutes for it to update on NPM.

**Comment by david-nguyen** [comment]
thank you for the quick fix

**Comment by david-nguyen** [comment]
Hmm it appears NPM still hasn't updated does it usually take a long time?

**Comment by VizuaaLOG** [comment]
Hmm I'll take a look later today. Should have updated by now.

**Comment by VizuaaLOG** [comment]
The latest version is now on NPM. Turns out I'm too used to Composer automatically updating using Git tags, I didn't republish the latest version to NPM.
