### ISSUE TITLE
Navbar Burger missing is-active class

### ISSUE THREAD

**Issue by david-nguyen** [VizuaaLOG/BulmaJS#36]
I think it would be an improvement to add the is-active class to the burger button - currently, it only applies the is-active class to the navbar-menu. If you would like I can work on a merge request.

https://bulma.io/documentation/components/navbar/#navbar-burger

**Comment by VizuaaLOG** [comment]
Hey David! That's a great idea. If you would like to create a PR that would be appreciated.

**Comment by wind930** [comment]
@VizuaaLOG  
Hello, I also encountered the above problems, and later found that the latest source code has been repaired, the version is also updated to 0.6.0, but NPM package still stay in 0.5.0 because there is no 0.6.0 tag's cause, causing NPM not to pull to the latest code, the trouble to update the version of NPM, thank you!

**Comment by VizuaaLOG** [comment]
Hey @wind930 0.6.0 is current still in development and so this change has not yet made it to NPM. I'm currently rewriting the docs for 0.6.0 which is taking longer than expected. If you would like to use the latest navbar change you can pull in the dev branch as everything should be working fine.

**Comment by david-nguyen** [comment]
Something seems a bit odd with the script on NPM, it seems to be the older version without applying the css class to the button

**Comment by VizuaaLOG** [comment]
@david-nguyen my reply above explains this. The version with the navbar update has not released yet.

**Comment by david-nguyen** [comment]
@VizuaaLOG sorry totally misread your previous comment!

**Comment by VizuaaLOG** [comment]
Hey, @david-nguyen and @wind930 apologies for the delay with this but life took over :(.

I finally had some time to finish the documentation overhaul and have now also pushed 0.6.0 to NPM. The `is-active` class should now be included within the NPM version.

As always, if you have any more feedback or find a typo within the shiny new docs please open a new issue.
