### ISSUE TITLE
Additional plugin ideas

### ISSUE THREAD

**Issue by VizuaaLOG** [VizuaaLOG/BulmaJS#47]
These are some ideas for additional plugins. These ideas are inspired from other similar libraries/frameworks.

+ **Tag input** Would provide an input field that users can use to type in 'tags'. Would make use of the Bulma input and tag components. (thanks to @chistel)

**If anyone has other ideas for plugins, please leave a comment. If it would suit this project well then I'll include it in the above list.**

**Comment by chistel** [comment]
How about input tag/autocomplete

**Comment by VizuaaLOG** [comment]
@chistel I like the idea of the tag input, as we can use the Bulma tag/input components/elements. I do also like the autocomplete idea, but what would the styling requirements be for that? I don't really want to force people to also include additional CSS other than what Bulma already offers.

**Comment by chistel** [comment]
the autocomplete is an optional plugin, so a little extra style would not kill.

**Comment by VizuaaLOG** [comment]
@chistel I understand your reasoning, but I'm trying to avoid the need to include JS and CSS with plugins. Unfortunately, an exception had to be made with the tabs plugin as it's a core feature of Bulma. I do like the idea though.

**Comment by chistel** [comment]
Good

**Comment by chistel** [comment]
I also was thinking about date and time selector plugin

**Comment by chistel** [comment]
a snackbar and a toast plugin would also be great.

**Comment by chistel** [comment]
> 
> 
> There is a [calendar](https://vizuaalog.github.io/BulmaJS/docs/0.7/calendar) plugin, it's using the CSS from Wikiki's Bulma extension. However, it has since updated it with a range of new features. It also has it's own Javascript code.
> 
> Because of the updates provided by Wikiki the Calendar plugin in BulmaJS will be depreciated and later removed in a future version.

its a little limited, as it supports only date without time.

**Comment by Wikiki** [comment]
Hi,

Not limited to dat anymore ;-)
The last version (v6) supports date / time and datetime

**Comment by Iamscalla** [comment]
Hmm ama check it out and give my review.

**Comment by VizuaaLOG** [comment]
The tag input is also available via @Wikiki extensions. I would advise using that instead as the goal for BulmaJS is to provide the JS for core Bulma features.

If anyone has any suggestions for functionality that can be added/adjusted on the existing plugins or if there's something in Bulma that may benefit from some JS magic please open a new issue.
