### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by lmannering** [VizuaaLOG/BulmaJS#57]
**Versions**
BulmaJS: 0.7.0
Browser: Chrome
Operating system: Mac

**Describe the bug**
After npm install, I cannot get the ES6 import to work. I get: 

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

I'm using browserify, babel and gulp:

```browserify('src/index.js')
        .transform('babelify')
        .bundle()
        .pipe(source('app.js')) // Readable Stream -> Stream Of Vinyl Files
        .pipe(buffer()) // Vinyl Files -> Buffered Vinyl Files
        .pipe(sourcemaps.init())
        .pipe(uglify().on('error', function (e) {
            console.log(e);
        }))
        .pipe(rename({extname: '.min.js'}))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('dist/'));
```

with the following config:

``` 
"babelify",
        {
          "presets": [
            [
              "@babel/preset-env",
              {
                "modules": "commonjs",
                "targets": {
                  "browsers": [
                    "last 2 versions",
                    "safari >= 7"
                  ]
                }
              }
            ]
          ],
          "plugins": [
            "transform-class-properties",
            "@babel/plugin-proposal-object-rest-spread"
          ],
          "sourceMaps": true
        }
```

Note: import * as _ from 'underscore' does not throw this error, which led me to believe there may be an error with the package exports?

**Comment by VizuaaLOG** [comment]
Does the error provide a specific file or that it's having trouble parsing?

If possible are you able to provide a test project that also causes this?

**Comment by lmannering** [comment]
Unfortunately I couldn't get the spread preset to work - you may have more luck than I had with this sandbox:
https://codesandbox.io/s/mqrn3q670j

This is the most I've been able to get out the browserify/babel debugger:

```
code/node_modules/@vizuaalog/bulmajs/src/bulma.js:3
import Bulma from './core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by VizuaaLOG** [comment]
The issue you're having seems to be quite common with babelify. There are various solutions but looks like it's more of a configuration issue than a problem with the package.

[Example](https://github.com/babel/babelify/issues/157)

This isn't an issue with the BulmaJS library as when you require it all processing is handled by your build process not BulmaJS's i.e. our build config is ignored.

Also, side note, the reason the sandbox isn't working I think is an issue with the version of parcel being used. I've not used parcel myself but seems to be a known issue and supposedly fixed in a new version.

**Comment by lmannering** [comment]
Thanks @VizuaaLOG, I thought it might be an issue with BulmaJS as the ES6 import from underscore works fine:

`import * as _ from 'underscore'`

I've posted an issue on SO to see if anyone can track it down, I'm still struggling to see what it is...

https://stackoverflow.com/questions/53037883/another-parseerror-import-and-export-may-appear-only-with-sourcetype-modu

**Comment by VizuaaLOG** [comment]
No problem, let me know how you get on. If it does turn out to be an issue with this package I'll be more than happy to reopen the issue.
