### ISSUE TITLE
Creating Modal with JS failed

### ISSUE THREAD

**Issue by timozander** [VizuaaLOG/BulmaJS#58]
**Versions**
BulmaJS: 0.5.0
Browser: Chrome 71
Operating system: Windows 10

**Describe the bug**
When trying to create a Modal dynamically with JavaScript, it does not work and shows the following error:
Uncaught TypeError: this.root.querySelector is not a function
    at Modal.findCloseButton (modal.js:74)
    at new Modal (modal.js:37)
    at Function.create (modal.js:50)
    at Object.create (core.js:26)
    at deleteEval (evaluations:210)
    at HTMLAnchorElement.onclick (VM12126 evaluations:173)

Creating a Modal via HTML works fine.

**To Reproduce**
1. Create HTML Document with Bulma.js included (pre-compiled master file)
2. Copy sample code for creating a Modal from doc
3. Run

**Expected behavior**
Modal should be shown

**Comment by diomed** [comment]
have you tried with newest version?

https://github.com/VizuaaLOG/BulmaJS/releases/tag/0.7.0

**Comment by timozander** [comment]
Sorry for my stupidity. Problem solved
