### ISSUE TITLE
Module not properly exported

### ISSUE THREAD

**Issue by alexcanana** [VizuaaLOG/BulmaJS#59]
**Versions**
BulmaJS: 0.7.0
Browser: irrelevant
Operating system: irrelevant

**Describe the bug**
Hello, I think there's a problem in the way you export the module. When I follow the documentation, I get the following error: 

`Uncaught TypeError: _bulmajs2.default.create is not a function`

I think it's because you don't export the module properly on [bulma.js](https://github.com/VizuaaLOG/BulmaJS/blob/master/src/bulma.js).

Also, I think you should remove `window.Bulma = Bulma;` from the same file. This should be left to the user to decide. And, if you import the library this way `import '@vizuaalog/bulmajs'`, it will work thanks to the windows assignment thus adding to the confusion.

I can submit a PR if needed.

Thank you!

**To Reproduce**

```
import Bulma from '@vizuaalog/bulmajs'

const modalTwo = Bulma.create('modal', {
  element: document.querySelector('#modal-example-2')
})
```

Produces

`Uncaught TypeError: _bulmajs2.default.create is not a function` 

**Fix**

On [bulma.js](https://github.com/VizuaaLOG/BulmaJS/blob/master/src/bulma.js) add the following line: 

`export default Bulma`

and remove the following line: 

`window.Bulma = Bulma;`

**Comment by VizuaaLOG** [comment]
Good spot! The export is wrong. I also think you're right about the window point. It was originally changed to make it easier to import, but there has been other changes that does make this irrelevant now.

I would really appreciate a PR if you would 👍
