### ISSUE TITLE
Message close icon

### ISSUE THREAD

**Issue by turbopixel** [VizuaaLOG/BulmaJS#6]
The icons in the [examples](https://vizuaalog.github.io/BulmaJS/documentation/message.html) are out of place.

Examples:
![image](https://user-images.githubusercontent.com/15839724/33429376-e7af1edc-d5cc-11e7-973e-05b164efdca0.png)
or 
![image](https://user-images.githubusercontent.com/15839724/33429437-211f67e4-d5cd-11e7-9555-35c64ef174e2.png)

On Chrome 62.0.3202.94 with MacOS 10.13.1

**Comment by VizuaaLOG** [comment]
Thanks for the report this is an issue with the docs. I'll double check the message plugin but I think it's just a docs issue.
