### ISSUE TITLE
Error on documentation example: Usage#Using Javascript

### ISSUE THREAD

**Issue by alexcanana** [VizuaaLOG/BulmaJS#60]
Hello,

I think there are some errors in the [**Usage**](https://vizuaalog.github.io/BulmaJS/docs/0.7/3-usage) page of the documentation.
On the **Using Javascript** section, shouldn't it be : 

```

import Modal from '@vizuaalog/bulmajs/src/plugins/Modal';

// instead of
import Modal from '@vizuaalog/bulma/src/plugins/Modal';

```

and

```

var modal = Modal.create({
    element: document.querySelector('#myModal')
});

// instead of
var modal = Bulma.create('modal', {
    element: document.querySelector('#myModal')
});

```

Thank you!

**Comment by VizuaaLOG** [comment]
Another good spot! Thank you. Both are correct. I'll get these updated later!
