### ISSUE TITLE
Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by dhoyek** [VizuaaLOG/BulmaJS#63]
**Versions**
BulmaJS: 
Browser: IE11
Operating system:  windows 10

**Describe the bug**
Object doesn't support property or method 'forEach' 
check screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/6195708/53054375-d7242400-34ac-11e9-9892-aca055bf3a01.png)

**Comment by VizuaaLOG** [comment]
Hi @dhoyek,

What version of BulmaJS are you using? Also is this with the source files or with the files in the `dist` folder?

**Comment by dhoyek** [comment]
I just used npm to install the version.

The error happens with the files in the dist folder. Referenced in SharePoint 2016 master page.

**Comment by alexcanana** [comment]
Hello,

I have found this [post](https://medium.com/@devlucky/nodelist-object-is-finally-an-iterator-cc529d6e2490) regarding this issue.

**Comment by VizuaaLOG** [comment]
Thank you for reporting this. IE11 doesn't support the `forEach` method being used in some plugins. This has been replaced with a helper method in `0.8.1`. This has been published to NPM.

If you have any further issues please open a new issue.

**Comment by Wikiki** [comment]
Hi,

as workaround you should be able to use ```[].forEach.call(elements, function(element) {})```

**Comment by VizuaaLOG** [comment]
@wikiki thanks for the suggestion. I do know of that method but personally I do not like how it looks, its not very readable in my opinion.

I've gone for a single helper method that wraps around a standard `for` loop.

Thanks for the suggestion though! 👍
