### ISSUE TITLE
Alert plugin improvements

### ISSUE THREAD

**Issue by alexcanana** [VizuaaLOG/BulmaJS#64]
Hi,

I think the alert plugin is a little too opiniated. It would be great if we could customize it a little bit more.

For instance :
- Being able not to have a header
- Being able to add extra classes to the elements of the modal (buttons, etc)
- Being able to prevent the modal from closing on onConfirm() and onCancel() events
- Being able to target the button that was clicked on onConfirm() and onCancel() events

What I suggest is adding a few more options. Maybe an object for the buttons ?

```
confirm: {
  'text': 'Confirm',
  'classes': 'is-link'
}

cancel: {
  'text': 'Cancel',
  'classes': 'is-danger'
}
```

To prevent the modal from being destroyed on onConfirm() and onCancel(), I suggest adding two more options :

```
destroyOnCancel: true|false // defaulted to true
destroyOnConfirm: true|false // defaulted to true
```

To target the button that was clicked on onConfirm() and onCancel() events, I suggest adding the event as a parameter on the 'click' event listener callback of the cancel and confim buttons.
Like so:

```
confirmButton.addEventListener('click', e => {
  this.onConfirm(e);
  this.destroyOnConfirm && this.destroy(); // related to previous suggestion
});

cancelButton.addEventListener('click', e => {
  this.onCancel(e);
  this.destroyOnCancel && this.destroy(); // related to previous suggestion
});
```

I have some of these features already coded, I can submit a PR if you're OK with the suggestions.

Waiting for your feedback, thanks !

**Comment by VizuaaLOG** [comment]
@alexcanana Thank you for your suggestion, you raise some very valid points.

Please do open a PR, so that we can check/review your changes.

In regards to preventing the alert from being destroyed - could I ask what's a use case for this? As far as I'm concerned an alert would only be single use as the contents of it would be different. I'm more than happy for this to be an option, just wanted a little bit of background on why it's needed.

Thanks again!

**Comment by alexcanana** [comment]
Hey there,

Right now I'm using the plugin to show a link on the confirm button.
The user clicks on it, and I just toggle the 'is-loading' class and the 'disabled' state to the button.

I could have used a simple modal, but the the alert plugin is there with the buttons, and everything, so why not use it ?

Another example of usage, could be that I click on the button, wait for an action to take place, and then proceed to destroy the alert, provide feedback, and whatnot depending on the action's result.

Have a nice week, thanks.

**Comment by alexcanana** [comment]
Hey @VizuaaLOG,

Quick question:
On your modal [example](https://vizuaalog.github.io/BulmaJS/docs/0.8/modal), how would you close the modal on the buttons' onClick without having to write another custom event handler?

Thanks in advance, cheers!

**Comment by VizuaaLOG** [comment]
@alexcanana hmmmm that's a good question. I don't think you can.

Im thinking maybe it needs to pass the modal instance to the button callbacks.

Unless you might be able to assign the modal to a variable. Then within the callback close it using the variable?

Although Im thinking the better way maybe to pass the modal to the callbacks.

**Comment by alexcanana** [comment]
OK, thank you.

I'm not sure passing the instance is very secure...
Maybe we can solve the security issue by exporting only what's needed from the instance ?

**Comment by VizuaaLOG** [comment]
I don't see what security concern this would have? All of the code is client side anyway?

**Comment by VizuaaLOG** [comment]
@alexcanana Thank you for your suggestions. These have been added to the master branch and the new [0.9](https://vizuaalog.github.io/BulmaJS/docs/0.9) documentation.

It's not on NPM yet, just want to test a little bit make sure everything is okay.

I've added the option for custom classes on the buttons, but do not feel like other elements require custom classes. The alert is using the modal behind the scenes so any style changes made to that via your application will automatically apply to the alert, keeping consistency etc.

Should your app require changing the styling of other model elements within the alert, a new `.alert` class has been added to alert popups allowing you to only target those in your CSS.

If you have any further suggestions, please open a new issue. BulmaJS will only get better with everyone's feedback. 👍

**Comment by alexcanana** [comment]
Not sure about the security, I'm no JS expert...

Awesome work, thank you!

**Comment by alexcanana** [comment]
Hey @VizuaaLOG,

I've been testing the alert plugin but I think there was a misunderstanding regarding my request about not destroying the modal.

I wanted to prevent the modal from closing. Just keep it open, until I decide it's time to hide it.
For example, wait for an ajax request callback, and then decide what to do depending on it's result.
