### ISSUE TITLE
Modal plugin - body 'is-clipped' does not work

### ISSUE THREAD

**Issue by alexcanana** [VizuaaLOG/BulmaJS#68]
**Bulma:** 0.7.4
**BulmaJS:** 0.8.0

Hello,

I noticed that that when opening a modal, an `is-clipped` class is added to the body.
Unfortunately, this does not clip the document.

The class should be added to the html tag instead.
Maybe this was changed in newer versions of Bulma?

**Solution**
On line 187 of modal.js, replace:

`document.body.classList.add('is-clipped');`

with

`document.documentElement.classList.add('is-clipped');`

And on line 200, replace :

`document.body.classList.remove('is-clipped');`
with
`document.documentElement.classList.remove('is-clipped');`

I can submit a PR if needed.

Thanks in advance.

**Comment by VizuaaLOG** [comment]
Thanks for reporting this. I think this may have changed in a recent version of Bulma.

I would appreciate a PR if you have the time. Or I can get this fixed in few days.

Thanks again 👍

**Comment by alexcanana** [comment]
I tried to submit the PR but the button is greyed out...
Will try again later.
