### ISSUE TITLE
Request: SideNav in Bulma

### ISSUE THREAD

**Issue by YacineAcme** [VizuaaLOG/BulmaJS#72]
**Is your feature request related to a problem? Please describe.**
I want to create a retractable menu, so basically you would click on the hamburger icon and the menu will appear on the left pushing the content on the right. Right now I am using the component sidenav of @angular/material [(link)](https://material.angular.io/components/sidenav/overview) but I don't want to use bulma and @angular/material together as I heard it's bad practice and it could result in css bugs.

**Describe the solution you'd like**
The solution would be to have a component sidenav integrated in the bulma css framework.

**Describe alternatives you've considered**
Many alternatives are available but as I said I don't want to mix multiple css frameworks
- @angular/material

**Additional context**
I am requesting this because I have a bulma-style navigation bar component at the top of my page and below it an @angular/material sidenav and I have a CSS problem where the sidenav content overlaps the navigation bar by few pixels.

**Comment by VizuaaLOG** [comment]
Hey @YacineAcme,

I think you meant to post this feature into the [primary Bulma CSS repository](https://github.com/jgthms/bulma). This repo is only for my Javascript extension to Bulma and doesn't contain any of the CSS code.

More than happy to add a Javascript plugin if it becomes part of the core Bulma CSS framework.

Please submit a new issue if you have any future suggestions! 👍
