### ISSUE TITLE
alert.js and modal.js do not work properly.

### ISSUE THREAD

**Issue by ubaid-dev** [VizuaaLOG/BulmaJS#73]
**Versions**
BulmaJS: 0.11.0
Browser: 74.0.3729.169 
Operating system: Window 10

**Describe the bug**
alert.js and modal.js do not work properly.

**To Reproduce**
1. Include alert.js or modal.js like a plugin
2. Try make someting

**Expected behavior**
Creating alert or modal popup as shown in documentation examples.

**Screenshots**
https://codepen.io/ubaid-dev/pen/RmevwO

**Comment by ubaid-dev** [comment]
![solution](https://user-images.githubusercontent.com/38039843/58634337-b82afe80-82f3-11e9-8dbc-9467f4dd75e8.JPG)

The problem in this method where config is second parameter not first. The first parameter is key (name of plugin).
The same problem occurs in other plugins. (notification.js, accordion.js, etc)

**Comment by VizuaaLOG** [comment]
Hey @ubaid-dev,

Thank you for reporting this, and looking into what may be causing it.

This has been fixed in master and will be included in the next release.
