### ISSUE TITLE
Unexpected Identifier when import bulmaJS

### ISSUE THREAD

**Issue by valentin-vogel** [VizuaaLOG/BulmaJS#80]
**Versions**
BulmaJS: 0.10.0
Browser: Chrome Latest
Operating system: Windows

**Describe the bug**
When import bulmaJS with ES6 method i got a syntax error:

import Bulma from './core' -> Unexpected Identifier

**To Reproduce**
1. Checkout https://github.com/prismicio/nextjs-website
2. Setup Project
3. Install and import bulma and sass
4. Install and import bulmaJS in layouts/index.js

**Expected behavior**
A directly working navbar.

Can you help me with this?

**Comment by VizuaaLOG** [comment]
Unexpected identifier would indicate your project is not processing the ES6 javascript files. Although ES6 is well supported with modern browsers they do not support the import syntax. So it does still need to be transpiled. This varies depending on your project but something like Babel is what you would use.

**Comment by valentin-vogel** [comment]
Thank you so much. I'm so stupid. I haven't notice that. Now it's working.
