### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by hovancik** [VizuaaLOG/BulmaJS#85]
**Versions**
BulmaJS: `"@vizuaalog/bulmajs": "^0.10.0",`
Browser: Chromium
Operating system: MacOS

I am with Ruby on Rails and using webpacker to serve JS. 

**Describe the bug**
I'm getting error when trying to use this library. Can't get any example to work so I guess I am doing something very stupid...

**To Reproduce**
HTML: 
```
    <div id="example-notification"></div>
```

JS:
```
import Bulma from '@vizuaalog/bulmajs'

Bulma.create('notification', {
  body: 'I am always visible until you close me manually.',
  parent: document.getElementById('dismissable-notification'),
  isDismissable: true
}).show()
```

```
Uncaught TypeError: Cannot read property 'appendChild' of null
   at Notification.DismissableComponent (dismissableComponent.js:106)
    at new Notification (notification.js:94)
    at Function.create (notification.js:42)
    at Object.create (core.js:25)
    at Module../app/javascript/packs/application.js (application.js:18)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

**Comment by VizuaaLOG** [comment]
Your HTML element has the ID `example-notification`. But your `parent` option is trying to get an element with the ID `dismissable-notification`. You'll need to change either your parent option or the ID on your HTML element.

**Comment by hovancik** [comment]
Hi and thanks for the reply. It must have been something else, because I've tried different examples from the docs but no component worked for me (didn't save the errors, though). 

Anyway I moved to another library.
