### ISSUE TITLE
Imported using Laravel Mix. Bulma is not defined

### ISSUE THREAD

**Issue by rognales** [VizuaaLOG/BulmaJS#86]
**Versions**
BulmaJS:  0.10
Browser:  Chrome 76.0.3809.132
Operating system: Windows 10

**Describe the issue**
dashboard:193 Uncaught ReferenceError: Bulma is not defined
    at HTMLButtonElement.<anonymous> (dashboard:193)

I'm using laravel mix to import this plugin. Component using DOM/standard Bulma works as expected. However, those that require Javascript intervention cannot work with above error message (modal. message, alert)

Thx,

**Comment by rognales** [comment]
Got it working. I use laravel [Laravel bootstrap.js](https://github.com/laravel/laravel/blob/5.8/resources/js/bootstrap.js) as reference.

In app.js,

```javascript
try {
    window.Bulma = require('@vizuaalog/bulmajs').default;
} catch (e) {}

**Comment by rognales** [comment]
How do close modal pragmatically? 

````javascript
var modal = Bulma.create('modal', {
    root: document.getElementById('modal-example-1'),
    title: 'Modal title 1',
    body: '<p class="image is-4by3"><img src="https://bulma.io/images/placeholders/1280x960.png" alt=""></p>',
    buttons: [
        {
            label: 'Save changes',
            classes: ['button', 'is-success'],
            onClick: function() { alert('Save button pressed'); }
        },
        {
            label: 'Close',
            classes: ['button', 'is-danger', 'is-outlined'],
            onClick: function() { this.close() }
        }
    ]
});

**Comment by VizuaaLOG** [comment]
As the modal instance has been assigned the `modal` variable. You can use `modal.close()`.

To keep things organised, please create a new issue is it's a different topic though 🙂 helps reduce any potential confusion.
