### ISSUE TITLE
Destroyed modal still listens on keyup event

### ISSUE THREAD

**Issue by luksurious** [VizuaaLOG/BulmaJS#88]
**Versions**
BulmaJS: 0.10.0
Browser: Any (Chrome/Firefox(
Operating system: Linux/Windows

**Describe the bug**
When a modal is destroyed the key event listener is not removed. Thus, if a key is typed afterwards on the page a JS error is raised because of the elements in the listener not existing anymore: `modal.js:193 Uncaught TypeError: Cannot read property 'classList' of null`

**To Reproduce**
1. Go to https://jsfiddle.net/2wtkp783/
2. Click on "Open Modal" to make sure a valid modal is created
3. Close modal
4. Click on "Destroy Modal"
5. Type something in the text box below
6. Observe JS error in browser console

**Expected behavior**
No error should be raised. The event listener should be removed on destroy.

**Screenshots**
![image](https://user-images.githubusercontent.com/1231010/67158192-cb3f7900-f33d-11e9-84af-609db19ca82e.png)

**Comment by VizuaaLOG** [comment]
Reopening and a reminder to port this back to 0.10.
